common:
    pg_bin_path: ENC[AES256_GCM,data:AqLKm5NeQg7X0BKXy1oxu4IVF6LXXOu04xbQligYTz5OSGI=,iv:pBYpJorNUcrdyQXPwF1thI34vhl+NEhRjmZU1zW7uaI=,tag:MfVNKLRDH6T3LXyUVhygHw==,type:str]
    tmp_dir: ENC[AES256_GCM,data:KWWgKg==,iv:b5vXcSIL9u34u83jIwHkSo6PH8Zbd6kUIM/VAQ15wo8=,tag:aTudpcyW3w8A9wsmaj0FEA==,type:str]
storage:
    type: ENC[AES256_GCM,data:5zZJClQB+tYR,iv:k2brJul3l8FNQWUg7SU6CgZ0eY3OFJSzIo0kjbZqXBU=,tag:iSqHSffA06GyfnONG5ljIw==,type:str]
    directory:
        path: ENC[AES256_GCM,data:t6U/68Sr,iv:sX51ObBESD787VU1l36gTousOi2wd8F0UypXYluxvwg=,tag:yT3kR1FSHzwDebIVtoaQYA==,type:str]
dump:
    #ENC[AES256_GCM,data:GceUiU+RUvwzs6rR5Bt7448EOmnX5GksazBzDXg9swxt87cEmw==,iv:S58bGGzI7XSfyTQ6iDCHhied29E+8L93B5D/zRn4sXQ=,tag:Ua8eGWu6PbgJtLrb4/bIeQ==,type:comment]
    pg_dump_options:
        dbname: ENC[AES256_GCM,data:utVDSH5MOCmNhOn7nubiQUSfaeYb4ia8UAWOLfq5Qp/cpCiFxSp4Q4hRLAkHOVV7LIW7NsRebJqRxIngi4ySZUiv0BnZFd1tLezeNQ==,iv:gynmsWC/LgJBWt4lKmDwVd+XZEVsuWDiQjIh1x/5IUg=,tag:dIDANxzysIC7aXV7hurmXQ==,type:str]
        jobs: ENC[AES256_GCM,data:Yg==,iv:9603kZzqyr2XLvFTdSpw6/Ppzugwf/e8v+peyOc/ql0=,tag:K+61Ap0LVZ8F/tbO6KdXnA==,type:int]
        #ENC[AES256_GCM,data:t/S0shSdpdqd/Lqrj+Uytz3bwFVjxb2poC81tAQo0dOfVjEOKs9XbvH8fCEei+utUZxEgw7KAwQ=,iv:XFQS2WlCq7yTt3SkHpngzpnW2Elc0tHV/zOqUXt3vA0=,tag:5etyQCGESIV4DCKePioLmw==,type:comment]
        table:
            - ENC[AES256_GCM,data:N6nUZBLvMo9n6p8kjygScIkj,iv:rRqwyavLnzIkIjlZjCH3T/RM/B4RJNXv+ENMKQy8jQI=,tag:SjlmS5jV0N7CNqN72uPS0g==,type:str]
    #ENC[AES256_GCM,data:aNZtdCN08TyaET2O4ir1y82koZdny2a1vq7M4g==,iv:XbG7+F7+Iho5oX/M/fBqMu92nhYSyFWStFjkMxrmnX0=,tag:DtedYGFVvwlEWe7KcmMcRQ==,type:comment]
    transformation:
        - ENC[AES256_GCM,data:kemF8xmwOvTMT8V/sA==,iv:q+GoSPOpyybZIe13UWk01MilxMfTZ/SZcUIX+DSzR60=,tag:dWEOKPGb2Y9UmeMNM6ktxw==,type:comment]
        - schema: ENC[AES256_GCM,data:zlAHtODY,iv:zu1zcvWdAVyo7Z3Nuc7x+u75KNaGtyvb/kPwEQS/rBk=,tag:HqEq7JCOwEXdVIc74F2mHg==,type:str]
          #ENC[AES256_GCM,data:XYah1x7iojdx7pQ=,iv:1Xvqg4/Hm0vVuwGARjw65IDkertYNbjqiH+QK+8pUd0=,tag:lLqFpXm0thObBvvlf71yXw==,type:comment]
          name: ENC[AES256_GCM,data:lo6kW+1gfaBurB4=,iv:zeqQP3z5MY5CHFng1TlyBadEw8WYE2gaBuPmSPlxxM4=,tag:oLP6qrU/3GYUdRYrpYqP1A==,type:str]
          #ENC[AES256_GCM,data:a88InOIH8O75aobZJ/pBNnKMJvo1lDSnPMA4Hcsh,iv:ALQUjflKpQykZ6c2NwcQQzCoEXpfoCjXsZdKmRR1A0Y=,tag:Y9fWMIJR0R5R61pe13hx7w==,type:comment]
          transformers:
            - name: ENC[AES256_GCM,data:e0ZlXTYW94E3lGSo,iv:JegIusTbKJI1fD4EQzcsAtawwXOUJ0a0O3+prDWmzyM=,tag:xyqarSjySg1qAFBIFhOY/A==,type:str]
              params:
                column: ENC[AES256_GCM,data:5r78HIrXsn+Q,iv:ToWJWvj9/dejmoMNiJ74tPZy65780BPL/81kIEFKQMM=,tag:CqB3Bl98E2jpBG2A2fcYtw==,type:str]
                min_length: ENC[AES256_GCM,data:qhc=,iv:uHho3PR3lUHl0bY+gQvw6iCgdHAT8UDCVEKXrID3n/0=,tag:CW5SXGSNxFS67A8qcsuWCA==,type:int]
                max_length: ENC[AES256_GCM,data:cAc=,iv:yPEvuJBjMD32YYzIAZpc3hMHR8l9BYcs8kWrFPvp7ck=,tag:R0uVXJrsObo2zGv8PoXl/w==,type:int]
                symbols: ENC[AES256_GCM,data:u6r470fv0k+hCg==,iv:shekwVYxjvF8iMq8+Z9mST7jxoWAaLZ1Hf0xaHyVDEg=,tag:ZAjUDhVumpLaHvYku8YEdg==,type:str]
                keep_null: ENC[AES256_GCM,data:xihi4uI=,iv:9KjJFdrqbyqClZizOjkNQvRc4Q1CYPG41/plgw60mnE=,tag:PxsFCmmT3k60kXv2wNHukw==,type:bool]
                engine: ENC[AES256_GCM,data:iyW1NFwS,iv:JUu1/QuC+ETE9G0rY+AYnOYCfj38H7ZV2SqCrElo4YM=,tag:qBpSXTJy7jaPBr9rbrrfng==,type:str]
            - name: ENC[AES256_GCM,data:MOiLYQSLG/Iz3e+hjA==,iv:1uQ8R14ePR44iQjbg47qbhqz27sEQAXj7THmZ4xEsFo=,tag:UjkC80udo9HhdVVVxf8e4Q==,type:str]
              params:
                column: ENC[AES256_GCM,data:5r78HIrXsn+Q,iv:ToWJWvj9/dejmoMNiJ74tPZy65780BPL/81kIEFKQMM=,tag:CqB3Bl98E2jpBG2A2fcYtw==,type:str]
                regexp: ENC[AES256_GCM,data:b+wA,iv:y82x0yrPLZiuGe0fKll+kBDgVEiE/5jpsOC0NLYQu9Y=,tag:JXfIrE/zTu33HqiKrXPTBg==,type:str]
                replace: ENC[AES256_GCM,data:8AaO,iv:+qr2eCrNGo3/okA3yNDjp76DRJHgEuJAnyGv/xVgVXI=,tag:bgdDoF8vek/0ZB2GVCx/gA==,type:str]
            - name: ENC[AES256_GCM,data:e0ZlXTYW94E3lGSo,iv:JegIusTbKJI1fD4EQzcsAtawwXOUJ0a0O3+prDWmzyM=,tag:xyqarSjySg1qAFBIFhOY/A==,type:str]
              params:
                column: ENC[AES256_GCM,data:fIWunhfHIA==,iv:NeQlJ+WuSjGT2RkLUwAC5UMhccBFT795aLT74pjILcU=,tag:COfmqFH+mfOmy1MLXoLR5Q==,type:str]
                min_length: ENC[AES256_GCM,data:1kA=,iv:QsARk1Zbnh8C98IKbQcYmMAoPBAIVbAKY07dBEV08Ug=,tag:iA7W55CZz9ID/MBmbJo1+Q==,type:int]
                max_length: ENC[AES256_GCM,data:skw=,iv:717W/kQeuAY5QdV7GyiiO7GchNCT6/nmBTNMkmT328c=,tag:FtebweSCgoEWFdMWwQpfXw==,type:int]
                symbols: ENC[AES256_GCM,data:u6r470fv0k+hCg==,iv:shekwVYxjvF8iMq8+Z9mST7jxoWAaLZ1Hf0xaHyVDEg=,tag:ZAjUDhVumpLaHvYku8YEdg==,type:str]
                keep_null: ENC[AES256_GCM,data:xihi4uI=,iv:9KjJFdrqbyqClZizOjkNQvRc4Q1CYPG41/plgw60mnE=,tag:PxsFCmmT3k60kXv2wNHukw==,type:bool]
                engine: ENC[AES256_GCM,data:iyW1NFwS,iv:JUu1/QuC+ETE9G0rY+AYnOYCfj38H7ZV2SqCrElo4YM=,tag:qBpSXTJy7jaPBr9rbrrfng==,type:str]
            - name: ENC[AES256_GCM,data:MOiLYQSLG/Iz3e+hjA==,iv:1uQ8R14ePR44iQjbg47qbhqz27sEQAXj7THmZ4xEsFo=,tag:UjkC80udo9HhdVVVxf8e4Q==,type:str]
              params:
                column: ENC[AES256_GCM,data:fIWunhfHIA==,iv:NeQlJ+WuSjGT2RkLUwAC5UMhccBFT795aLT74pjILcU=,tag:COfmqFH+mfOmy1MLXoLR5Q==,type:str]
                regexp: ENC[AES256_GCM,data:b+wA,iv:y82x0yrPLZiuGe0fKll+kBDgVEiE/5jpsOC0NLYQu9Y=,tag:JXfIrE/zTu33HqiKrXPTBg==,type:str]
                replace: ENC[AES256_GCM,data:R84=,iv:sUc1oeQTlp3nYr2r0gNG9e+8Xfy6DiqQi0tVrQiQ198=,tag:U6v2vyc1VaXqFLAehgsfTA==,type:str]
            - name: ENC[AES256_GCM,data:7k7VQWMIkVK14lA=,iv:2IL9PIN8gq/akSEsQNxqFqCVeDbhV9H57hKrRuDAJL8=,tag:jJMz3CYhIkM0CO0oAnn97g==,type:str]
              params:
                column: ENC[AES256_GCM,data:MKyRFbWjsKU=,iv:Ylp5lE+mtTPh5vqTnanewUk6bPlGO7xulrWi6vc8iyE=,tag:4N0akxWWDFTBuo1HS1PcjA==,type:str]
                engine: ENC[AES256_GCM,data:iyW1NFwS,iv:JUu1/QuC+ETE9G0rY+AYnOYCfj38H7ZV2SqCrElo4YM=,tag:qBpSXTJy7jaPBr9rbrrfng==,type:str]
                max_random_length: ENC[AES256_GCM,data:8IU=,iv:MfGaq4cbvbxA4j5g4dRZ3zYvPaJ2ReaFUw+ZeE6afzw=,tag:Sw4kaa/ykExagbPo+lhhRw==,type:int]
            - name: ENC[AES256_GCM,data:4UgMI+fSgo03mIkQ,iv:kDC/3BsvLmhrlCDYIi+FFLe5wmOdHGqUyXojjIcYMIg=,tag:SpV5jQKd1e5prW1iAdvP8Q==,type:str]
              params:
                columns:
                    - name: ENC[AES256_GCM,data:TaQJ53XcoA==,iv:m338JS+L4wbYcgVfwkm8AH+pEEkCPviuSEF4Qe5pgH4=,tag:lBXek3OouCjyClMjyPcDiA==,type:str]
                      template: ENC[AES256_GCM,data:IRBH5MBP/YhBNXO2Ey4K4hKSW4zL1y5IeeXbH2txwns=,iv:Z45vt6y8YIa5WpnK8hd3gFqUj26pPrtj+LFcLCRkNvI=,tag:I7ZC+0ZHC7uHRNjvXMuOMg==,type:str]
            - name: ENC[AES256_GCM,data:e0ZlXTYW94E3lGSo,iv:JegIusTbKJI1fD4EQzcsAtawwXOUJ0a0O3+prDWmzyM=,tag:xyqarSjySg1qAFBIFhOY/A==,type:str]
              params:
                column: ENC[AES256_GCM,data:qu2i/WiLC9mkwEk8,iv:Qf9fgL8Fr+P3rWFphtQ6Qh02JGL6+ua2dwLBN0jESpc=,tag:cvPU6THkEXLW5uzOb9ITpQ==,type:str]
                min_length: ENC[AES256_GCM,data:GSM=,iv:aEEBCplXx9g0skBLvWY+NRIF1gFVOuO4GptRxgKFTNk=,tag:0hvytpeT3BdDd9q4Jvy+JQ==,type:int]
                max_length: ENC[AES256_GCM,data:Yx8=,iv:lshYpsce4E3jWV/ra522KFzKoHHpTdbIBqj3XCa2Qrk=,tag:7KzaDn8UlaYtcnu4MOoJXQ==,type:int]
                symbols: ENC[AES256_GCM,data:u6r470fv0k+hCg==,iv:shekwVYxjvF8iMq8+Z9mST7jxoWAaLZ1Hf0xaHyVDEg=,tag:ZAjUDhVumpLaHvYku8YEdg==,type:str]
                keep_null: ENC[AES256_GCM,data:xihi4uI=,iv:9KjJFdrqbyqClZizOjkNQvRc4Q1CYPG41/plgw60mnE=,tag:PxsFCmmT3k60kXv2wNHukw==,type:bool]
                engine: ENC[AES256_GCM,data:iyW1NFwS,iv:JUu1/QuC+ETE9G0rY+AYnOYCfj38H7ZV2SqCrElo4YM=,tag:qBpSXTJy7jaPBr9rbrrfng==,type:str]
            - name: ENC[AES256_GCM,data:e0ZlXTYW94E3lGSo,iv:JegIusTbKJI1fD4EQzcsAtawwXOUJ0a0O3+prDWmzyM=,tag:xyqarSjySg1qAFBIFhOY/A==,type:str]
              params:
                column: ENC[AES256_GCM,data:2jD2410EiEo1,iv:3CtIrK2PmuNWAPnC4d8AGDmHCuS4Y7PfUKS1spS4euc=,tag:WKmGamz3MSK2xtj/Wkv25g==,type:str]
                min_length: ENC[AES256_GCM,data:Hr8=,iv:dWx02ZIWGTw1dgeap4NNXfLWyTCns4d2izGX8AKXTMA=,tag:PggTwuDAegxcQEXLMc8+mg==,type:int]
                max_length: ENC[AES256_GCM,data:pIo=,iv:TCnTiE6skWNotH/JZw0TvVoUDPg36UqmVAB4OWd7SDA=,tag:WyhKm06NEAXMqumibb4pzQ==,type:int]
                symbols: ENC[AES256_GCM,data:u6r470fv0k+hCg==,iv:shekwVYxjvF8iMq8+Z9mST7jxoWAaLZ1Hf0xaHyVDEg=,tag:ZAjUDhVumpLaHvYku8YEdg==,type:str]
                keep_null: ENC[AES256_GCM,data:xihi4uI=,iv:9KjJFdrqbyqClZizOjkNQvRc4Q1CYPG41/plgw60mnE=,tag:PxsFCmmT3k60kXv2wNHukw==,type:bool]
                engine: ENC[AES256_GCM,data:iyW1NFwS,iv:JUu1/QuC+ETE9G0rY+AYnOYCfj38H7ZV2SqCrElo4YM=,tag:qBpSXTJy7jaPBr9rbrrfng==,type:str]
            - name: ENC[AES256_GCM,data:e0ZlXTYW94E3lGSo,iv:JegIusTbKJI1fD4EQzcsAtawwXOUJ0a0O3+prDWmzyM=,tag:xyqarSjySg1qAFBIFhOY/A==,type:str]
              params:
                column: ENC[AES256_GCM,data:2QRfg5x8SrGX,iv:Ul+2VflicItFElrfFh9EBSmqDscBXE6pSFkBZRHI7AM=,tag:GgBEvBbKVDQctaT6wNpyfw==,type:str]
                min_length: ENC[AES256_GCM,data:W9c=,iv:EMJuuuVGrzAmbz9Hop4PSuJhgpRdNKF6f+PIXmax5nk=,tag:9ifiXn2kXCKv+IEnKvL/iA==,type:int]
                max_length: ENC[AES256_GCM,data:sQU=,iv:U8FlUKw2tTDhPlRixrZUTLleOk7+cYARnU7qrbihZD8=,tag:SYeLehhyIGowgfHdljJ7qQ==,type:int]
                symbols: ENC[AES256_GCM,data:u6r470fv0k+hCg==,iv:shekwVYxjvF8iMq8+Z9mST7jxoWAaLZ1Hf0xaHyVDEg=,tag:ZAjUDhVumpLaHvYku8YEdg==,type:str]
                keep_null: ENC[AES256_GCM,data:xihi4uI=,iv:9KjJFdrqbyqClZizOjkNQvRc4Q1CYPG41/plgw60mnE=,tag:PxsFCmmT3k60kXv2wNHukw==,type:bool]
                engine: ENC[AES256_GCM,data:iyW1NFwS,iv:JUu1/QuC+ETE9G0rY+AYnOYCfj38H7ZV2SqCrElo4YM=,tag:qBpSXTJy7jaPBr9rbrrfng==,type:str]
            - name: ENC[AES256_GCM,data:Zesrw5sxAEY7k5s=,iv:uYb+AoDwLLhMhZ7cX+V4PNvhL2MKDUxybWxtbi3UoPA=,tag:xXzB/iD2vKWlu3vUdiIYzw==,type:str]
              params:
                columns:
                    - name: ENC[AES256_GCM,data:G30p+A2ATkbG,iv:E6sZ4W6jjOMF5Z9Kqryb4pZ5GYDouGoHHOhQv7n9zxU=,tag:jowN7w990EYHdgZupBhH+g==,type:str]
                      template: ENC[AES256_GCM,data:qmkFnFd4KNWV67XuqF1cVam99Q6aufx98H0isbYGIfpULxa7ydNUkd4TOuQ107mxy0IcJmTnCA==,iv:EXTxRyxLpDligMC1w+CeAJXaYOS3QJ+VRrl6BG1ZdgY=,tag:R5G/VxMbUQvfYEQcBMhPWA==,type:str]
                      keep_null: ENC[AES256_GCM,data:iGXubfE=,iv:W20fCTFnN3dKG071Qiu1ABoZjj1jBupRh9KTTXNABK4=,tag:EtA9OgrrfKCiE2trJ1GDtw==,type:bool]
            - name: ENC[AES256_GCM,data:Zesrw5sxAEY7k5s=,iv:uYb+AoDwLLhMhZ7cX+V4PNvhL2MKDUxybWxtbi3UoPA=,tag:xXzB/iD2vKWlu3vUdiIYzw==,type:str]
              params:
                columns:
                    - name: ENC[AES256_GCM,data:qq9Nvf732B/mhgM=,iv:DEY858HENMlwTfAFg9ASZ0l4HR7yAIh33UIZx7EbV7w=,tag:Km/tC2q0E1Tixzn/fUncTw==,type:str]
                      template: ENC[AES256_GCM,data:U4DxttQIOQBj,iv:WM4tz7e+10Fi7EV8GFH4zBwZeSMqNYya3y+oWwRw1lU=,tag:hncbRIIhNSY6WnER0ovpTg==,type:str]
                      keep_null: ENC[AES256_GCM,data:iGXubfE=,iv:W20fCTFnN3dKG071Qiu1ABoZjj1jBupRh9KTTXNABK4=,tag:EtA9OgrrfKCiE2trJ1GDtw==,type:bool]
            - name: ENC[AES256_GCM,data:TrDaFneEePS5,iv:h5XVu9KX5eFtMgOqW/I9vKcDW+l8XBE1IwareXn+LDs=,tag:Nw6C0pp2X7bHUq6m4l/XkA==,type:str]
              #ENC[AES256_GCM,data:BQ2ldv1VArANPGuCWLYs0v9vFA6vZGU=,iv:qPu1iWHIfvhQbC4gT6X9tKpogE7iml6ufztjMJymuyQ=,tag:17JzuRdfWPckFytn7laDNQ==,type:comment]
              params:
                max_ratio: ENC[AES256_GCM,data:7/qS9ygGnDy1Or2tnktmBpIz3g==,iv:G+ezhYBYKgJOcBnN8XiUlXKIT03W88NPydLz3BvHhgQ=,tag:F2cUx9Z7qqIX2PmCPRlmXQ==,type:str]
                #ENC[AES256_GCM,data:lFJWkWusSYGfYSFVwx01Peryr7Gnq2bYQ17VBB7AuicfKwRmmzlGEABULQMjKwf8ZANDjXBMIJUMnPneFGkiawyOGeZHSak=,iv:bIWdmbMzu3YarctEx5hydi2IP9SnG5yDrFeFmbjL3pw=,tag:tfXcHQviOchO/3hkka+/hg==,type:comment]
                column: ENC[AES256_GCM,data:9c1x5PQATn6SgHQ=,iv:56Zw76BwdhzF/oBukjmGkPoyC8U4Tzb8gjWmk1qJDIg=,tag:GlFX1lhwp+O1b8TTEuF03g==,type:str]
            - name: ENC[AES256_GCM,data:Zesrw5sxAEY7k5s=,iv:uYb+AoDwLLhMhZ7cX+V4PNvhL2MKDUxybWxtbi3UoPA=,tag:xXzB/iD2vKWlu3vUdiIYzw==,type:str]
              params:
                columns:
                    - name: ENC[AES256_GCM,data:ash5p0+E8P2UI/OG,iv:IPQbZmDLswlYsDSscTyYwZpJEgY74/ikdlLQbCrP9MM=,tag:FfL/FfbZ8KSBzMsEBu6ctg==,type:str]
                      template: ENC[AES256_GCM,data:IxXZPdjXkcVmPZGv,iv:E6ikCTJ0KAQ4DcWOgLsiLLPWBOF3wM8Vs18IJ6D//vY=,tag:1TIDyx+YNcO+S0CNCfgzBw==,type:str]
                      keep_null: ENC[AES256_GCM,data:iGXubfE=,iv:W20fCTFnN3dKG071Qiu1ABoZjj1jBupRh9KTTXNABK4=,tag:EtA9OgrrfKCiE2trJ1GDtw==,type:bool]
            - name: ENC[AES256_GCM,data:Zesrw5sxAEY7k5s=,iv:uYb+AoDwLLhMhZ7cX+V4PNvhL2MKDUxybWxtbi3UoPA=,tag:xXzB/iD2vKWlu3vUdiIYzw==,type:str]
              params:
                columns:
                    - name: ENC[AES256_GCM,data:B29ccr+5kQQbxV2e,iv:jSrGwiy8vxhuFnU7sU33EarjFan0epYN/2n8YJkM+94=,tag:S5hple9gNa3VvFrR20tFFA==,type:str]
                      template: ENC[AES256_GCM,data:U4DxttQIOQBj,iv:WM4tz7e+10Fi7EV8GFH4zBwZeSMqNYya3y+oWwRw1lU=,tag:hncbRIIhNSY6WnER0ovpTg==,type:str]
                      keep_null: ENC[AES256_GCM,data:iGXubfE=,iv:W20fCTFnN3dKG071Qiu1ABoZjj1jBupRh9KTTXNABK4=,tag:EtA9OgrrfKCiE2trJ1GDtw==,type:bool]
            - name: ENC[AES256_GCM,data:Zesrw5sxAEY7k5s=,iv:uYb+AoDwLLhMhZ7cX+V4PNvhL2MKDUxybWxtbi3UoPA=,tag:xXzB/iD2vKWlu3vUdiIYzw==,type:str]
              params:
                columns:
                    - name: ENC[AES256_GCM,data:v5yaze/JAP23ytLiQOeztA==,iv:eF/yd0pESWRokRd203vLtTX9JFvtpS3aZn4JcpFSqkg=,tag:4scJYdL21eUPTvrUtBDrlg==,type:str]
                      template: ENC[AES256_GCM,data:IArVtLR9pOqmlA==,iv:1XXP9FxPyz0tbApqjn2TGv9u2xZOnYx22D2CB0+gGdg=,tag:eNphFPEBYisbi8YlRaD8xA==,type:str]
                      keep_null: ENC[AES256_GCM,data:iGXubfE=,iv:W20fCTFnN3dKG071Qiu1ABoZjj1jBupRh9KTTXNABK4=,tag:EtA9OgrrfKCiE2trJ1GDtw==,type:bool]
restore:
    #ENC[AES256_GCM,data:4lQYxkXKrhH16clbtKVOeZZeb/G61a4gWsezuIbGDKYlgwelhvaKUts6ikF5XRv2dmA4LnP2iido8/l63hYGkbe/5g==,iv:5Dc1TguE6kDCdZ1djzCQy/7YfxwmNKFUEW61dV5Ur98=,tag:aY/x1Niu08H8Hm6jadyxKA==,type:comment]
    pg_restore_options:
        jobs: ENC[AES256_GCM,data:LSs=,iv:PlW4acxGlwYQ7Cmjy0Hviv/MkN33Oun6nlrNKciJ058=,tag:xfhxuCBIiJ9O3mHiF3QyHw==,type:int]
        clean: ENC[AES256_GCM,data:kyYRNg==,iv:Y/u3GoDCUQURNSswRb5m9+ofmeDFW5GFHg7UdWFnei4=,tag:XQNdbDF7TMFEWqvTbzlW5g==,type:bool]
        if-exists: ENC[AES256_GCM,data:Xl3iDQ==,iv:eDyL42se/zpXnvWKMmFTukpAB2SLzxRIAnrOWbFHINc=,tag:/z9RUdpiGH7DPR1FB0/TqA==,type:bool]
        dbname: ENC[AES256_GCM,data:OQFN+ewi1P9rD/Tl04LYAJ2WpUWx9GZ6FMQpQe9r/fJSrAror6ypcPJtUHOg8M7Jyp19CIElZ1uREYFMQWWDlXaVRk6gB5019hQLuTBpw580JlhsdC10Ig==,iv:gMPBSJnR5Rw5VV08PzJVS14ij5WLHW7ka9PiXHDJh5o=,tag:/pzipok4CTbVN+7IjLY1xg==,type:str]
sops:
    age:
        - recipient: age10wyyzvxe6n742jlwwvxw800nlq9dlwxdm6ugnkguka46ljywc46qzkefwj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSS2N4Qm5ncWRTMU5Kai9t
            Z1ZjTzZyeldZUHFzN1NRZ0dqbTBsS2NPL1ZVCmdkaUJKeHJvM0RQS0thQ01wM3NP
            VjRxcGhIYkFhK0g5bUdCbjUvWHQyQ0kKLS0tIDcxUUpacTlGSUYxbTZpUjhncEtG
            TFo4ME5KVFJZa3pkS21LSWNkSTNKUUUK4IVv4YSXhn1jr7e9lQ6LEuCnaMNuSu/w
            71yalcphwLeedXoVTw5cFcjCChbkK3gkrO2ewy0Vb8HrNCnrT84EBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rvzeaqzh492kjgr0ly3800myzuddlh74u92vj9yf8l4l393ay9vsmtrqk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSG96UDh5UnE4ZVM3M3RJ
            M09SUEZZNVp1VVpTSWNpVmE3bE5wYWNhbTE0CkFUMHdKNjZIaG1VMXFqaENyS1M0
            WGgxYmVrT21iUTd3YVZKWS9ZcjR0eFkKLS0tIDZ4VXMrb3ZKay9yWVBqQ2h4T3Jm
            Q2Z6djRSOWthbTluSjh6UWFEZkxmVmcKDiS5fAVq+YAwv+kvpO20rD7blJbOdy5C
            gsDT800hRKaWLFsdaLQgv8vFLHR67n5m1Q1PuIVNr3EoOEWjtkH57A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hptgy6gy7q3rxr0g2jfpzfmqq8nr5tczwglfgehcujyxyf763ytqwky6zz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUd1pmakEzR3FlWFU0NVlZ
            ZmswWFNXUEFEV0pUSzVaQW1Ma2VUR1ZhWW1BCkxpU00yWjFWUUZiaEFYbEZQaHBS
            K0NRUEh0Q1c0aDB4MEkyTFYrYWJiR2cKLS0tIHFpNEhERG1RajlVNDhvTVhvRGww
            T1k2bVBxdWJkclNMVGNuV0ZvUTlnUlEKQMIwE9mXKKbu2RNm6egnr5HimHAXL8li
            LFMvcmjIlgMHeuz8f2l7zK1qjJzJDoCRVN2rMeuY8lU8koZLWodC1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age108cazlf829cpvu2qz8kuvq3sadxf9tr88epm30vxp4c0nnxumads0guwml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNUVuUEJWUzk3d21mSDg2
            RmN0UFBPZUhtamhPclN0NHRFNXpYTk9jTlNnCjgyZHRrSFRsU0p3R3FvUEF0Zk0x
            NEVhdkN6dFpTejhmNnVBU01RTStSSDQKLS0tIFRxSkdJU1h1OUFadXdkOW0wTit6
            THpWTEt1MUNHR2F4cXpVemdqVXJrR1kKrXu2BArewVHF0b1V0c98eHkQq+AVZjqm
            jXWxLMg14+tv2WuJIGXYXpcq60u8VNRtygLtyJcFNX1iKmWVkFQdkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T06:51:46Z"
    mac: ENC[AES256_GCM,data:bahF58L1bub91wE6Nt3xAVVL8tld7VY8Pn9ibE3IlAu+dHWmJDKHoenVGqhdGTFswLuLIYJc0bOSCpYZr3xYWN2CSN7dOm6OSBnrYZxOjDnKVwyyNFSPSBhYeE/I0iHaJ8bxlIKe5agQEWgT3KQx3KFzJMpXNL29vBZQK0egdis=,iv:xMGEp315YdfYMcLjc8Fiq9oIDiccg1Uglu3H1vbw/4k=,tag:vWoX9Tz2Hf5K9RJnSs0n7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
